<a href="https://colab.research.google.com/github/basha-dev-coder/Machinelearning/blob/data_visuals/Plotly_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tf.__version__

'2.7.0'

In [2]:
indices = [0,1,2]
depth = 4

tf.one_hot(indices=indices,depth=len(indices),on_value=2.0,axis=-1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]], dtype=float32)>

In [3]:
tf.TensorShape(tf.ones(shape=[11,3,3]).shape) , tf.zeros(shape=[1,11])

(TensorShape([11, 3, 3]),
 <tf.Tensor: shape=(1, 11), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>)

In [4]:
tf.constant([1.0,2.0,3.0]).shape

TensorShape([3])

In [5]:
tf.rank(tf.ones(shape=[11,3,3]))

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [6]:
import datetime
tf.timestamp(datetime.datetime.now().strftime('%Y-%m-%d'))

<tf.Tensor: shape=(), dtype=float64, numpy=1641247709.42935>

In [7]:
datetime.datetime.now().strftime('%Y-%m-%d')

'2022-01-03'

In [8]:

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.boston_housing.load_data(
    path='boston_housing.npz', test_split=0.2, seed=42
)

In [9]:
tf.keras.layers.Dense(100,name="hidden_layer"),
model = tf.keras.Sequential([
    tf.keras.layers.Dense(200), 
  tf.keras.layers.Dense(200), 
  tf.keras.layers.Dense(150),
  tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(1,name="output_layer")
])


In [10]:
model.compile(loss = tf.keras.losses.mean_squared_error,
              optimizer=tf.keras.optimizers.Adam(),
              metrics=["mse"])

In [11]:
#history = model.fit(x=x_train,y=y_train,epochs=100)

In [12]:
#model.evaluate(x_test,y_test)

In [13]:
# import pandas as pd
# import matplotlib.pyplot as plt
# pd.DataFrame(history.history).plot()
# plt.ylabel('Loss')
# plt.xlabel('Epochs')

In [14]:
from IPython.display import clear_output
class Customcallback(tf.keras.callbacks.Callback):
  def on_epoch_begin(self, epoch, logs):
      #clear_output(wait=True)
      #pred_prob = model.predict(x_test)
      print(f"epochs begins {epoch+1}")

  def on_epoch_end(self, epoch, logs):
    #clear_output(wait=True)
    #pred_prob = model.predict(x_test)
    #loss = (logs["loss"])
    print(f"epoch number is {epoch+1}")

  def on_batch_end(self, batch, logs):
    #clear_output(wait=True)
    #pred_prob = model.predict(x_test)
    #loss = (logs["loss"])
    print(f"\n batch number is {batch+1} and logs is {logs}")

  def on_train_end(self, logs):
    print(f"{logs}")


In [15]:
model.fit(x_train,y_train,callbacks=[Customcallback()],epochs=1)

epochs begins 1

 batch number is 1 and logs is {'loss': 20459.283203125, 'mse': 20459.283203125}
 1/13 [=>............................] - ETA: 13s - loss: 20459.2832 - mse: 20459.2832
 batch number is 2 and logs is {'loss': 45567.0, 'mse': 45567.0}

 batch number is 3 and logs is {'loss': 36726.53125, 'mse': 36726.53125}

 batch number is 4 and logs is {'loss': 28109.294921875, 'mse': 28109.294921875}

 batch number is 5 and logs is {'loss': 26960.087890625, 'mse': 26960.087890625}

 batch number is 6 and logs is {'loss': 26066.1484375, 'mse': 26066.1484375}

 batch number is 7 and logs is {'loss': 23926.458984375, 'mse': 23926.458984375}

 batch number is 8 and logs is {'loss': 21155.4453125, 'mse': 21155.4453125}

 batch number is 9 and logs is {'loss': 18879.96484375, 'mse': 18879.96484375}
 9/13 [===================>..........] - ETA: 0s - loss: 18879.9648 - mse: 18879.9648 
 batch number is 10 and logs is {'loss': 17552.33203125, 'mse': 17552.33203125}

 batch number is 11 and lo

In [16]:
history = model.fit(x_train,y_train,epochs=50)

Epoch 1/50
13/13 [==============================] - 0s 5ms/step - loss: 1611.7443 - mse: 1611.7443
Epoch 2/50
13/13 [==============================] - 0s 5ms/step - loss: 556.2035 - mse: 556.2035
Epoch 3/50
13/13 [==============================] - 0s 7ms/step - loss: 165.1052 - mse: 165.1052
Epoch 4/50
13/13 [==============================] - 0s 6ms/step - loss: 122.7797 - mse: 122.7797
Epoch 5/50
13/13 [==============================] - 0s 8ms/step - loss: 77.0913 - mse: 77.0913
Epoch 6/50
13/13 [==============================] - 0s 8ms/step - loss: 74.9573 - mse: 74.9573
Epoch 7/50
13/13 [==============================] - 0s 5ms/step - loss: 71.6298 - mse: 71.6298
Epoch 8/50
13/13 [==============================] - 0s 11ms/step - loss: 70.9748 - mse: 70.9748
Epoch 9/50
13/13 [==============================] - 0s 6ms/step - loss: 69.0237 - mse: 69.0237
Epoch 10/50
13/13 [==============================] - 0s 7ms/step - loss: 68.9729 - mse: 68.9729
Epoch 11/50
13/13 [===================

In [17]:
!pip install plotly==5.5.0

In [18]:
import plotly.express as ply 

In [19]:
ply.scatter( x=range(0,50),y=history.history['mse'])

In [20]:
pd = ply.data.iris()

In [21]:
ply.scatter(pd,x="sepal_width",y="sepal_length",color="species",size="petal_length",hover_data=["petal_width"])

In [22]:
ply.scatter(pd,x="sepal_width",y="sepal_length",color="petal_length")

In [23]:
ply.scatter(pd,x="sepal_width",y="sepal_length",color="species",marginal_x="histogram",marginal_y="rug")

In [24]:
import plotly.express as px
df = px.data.tips()
fig = px.scatter(df, x="total_bill", y="tip", color="smoker", facet_col="sex", facet_row="time")
fig.show()

In [25]:
df = ply.data.gapminder().query("continent == 'Oceania'")
fig = ply.line(df, x='year', y='lifeExp', color='country')
fig.show()


In [38]:
import plotly.graph_objects as go
from plotly import data

df = data.tips()

fig = go.Figure(go.Histogram2d(
        x=df.total_bill,
        y=df.tip,
       texttemplate="%{z}"
        
    ))

fig.show()

In [27]:
import plotly as plot
plot.__version__

'5.5.0'